return {}
-- return {
--   "nvim-lualine/lualine.nvim",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   opts = {
--     options = {
--       theme = "catppuccin",
--       icons_enabled = true,
--       component_separators = "|",
--       section_separators = { left = "", right = "" },
--       disabled_filetypes = {
--         statusline = {},
--         winbar = {},
--       },
--       ignore_focus = {},
--       always_divide_middle = true,
--       globalstatus = false,
--       refresh = {
--         statusline = 1000,
--         tabline = 1000,
--         winbar = 1000,
--       },
--     },
--     sections = {
--       lualine_a = {
--         { "mode", separator = { left = "" }, right_padding = 2 },
--       },
--       lualine_b = { "branch", "diff", "diagnostics" },
--       lualine_c = { { "filename", path = 1 } },
--       lualine_x = { "encoding", "filetype" },
--       lualine_y = { "progress" },
--       lualine_z = {
--         { "location", separator = { right = "" }, left_padding = 2 },
--       },
--     },
--     inactive_sections = {
--       lualine_a = {},
--       lualine_b = {},
--       lualine_c = { "filename" },
--       lualine_x = { "location" },
--       lualine_y = {},
--       lualine_z = {},
--     },
--     tabline = {},
--     winbar = {},
--     inactive_winbar = {},
--     extensions = {},
--   },
-- }
